version: "3"
services:
  mysql:
    container_name: "mysql"
    image: mysql:latest
    volumes:
      - "./mysql-data/db:/var/lib/mysql" 
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: marveldb
      MYSQL_USER: marvel
      MYSQL_PASSWORD: marvelpass
    networks:
      -  marvel-network
  python:
    restart: always
    build: .
    container_name: "python"
    tty: true
    depends_on:
      - mysql
    networks:
      -  marvel-network
networks:
   marvel-network:
    driver: bridge
